### ISSUE TITLE
[Dúvida] O projeto vai continuar open source?

### ISSUE THREAD

**Issue by eduardosoareszup** [teamsevenn/uready.app#1]
Tem algum planejamento de como vão prosseguir agora? Vai continuar open source?

**Comment by eduardosoareszup** [comment]
Aproveitando, ficou muito legal o projeto de vocês! Parabéns!

**Comment by isaachbn** [comment]
@eduardosoareszup agradecemos seu interesse no projeto, alguns componentes iremos trabalharmos open source para comunidade. Fique acompanhando o [team](https://github.com/teamsevenn) que novos projetos irão ser  gerados. Esse em questão estamos fechando por aqui.
